Consulting/Controllers/HKContractController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Consulting.Models;

namespace Consulting.Controllers
{
    public class HKContractController : Controller
    {
        private readonly ConsultingContext _context;

        public HKContractController(ConsultingContext context)
        {
            _context = context;
        }

        // GET: HKContract
        public async Task<IActionResult> Index()
        {
            var consultingContext = _context.Contract.Include(c => c.Customer);
            return View(await consultingContext.ToListAsync());
        }

        // GET: HKContract/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contract = await _context.Contract
                .Include(c => c.Customer)
                .FirstOrDefaultAsync(m => m.ContractId == id);
            if (contract == null)
            {
                return NotFound();
            }

            return View(contract);
        }

        // GET: HKContract/newFunction/5
        public async Task<IActionResult> newFunction(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contract = await _context.Contract
                .Include(c => c.Customer)
                .FirstOrDefaultAsync(m => m.ContractId == id);
            if (contract == null)
            {
                return NotFound();
            }

            return View(contract);
        }



        // GET: HKContract/Create
        public IActionResult Create()
        {
            ViewData["CustomerId"] = new SelectList(_context.Customer, "CustomerId", "CustomerId");
            return View();
        }

        // POST: HKContract/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ContractId,CustomerId,Name,StartDate,DaysDuration,QuotedPrice,Closed,TotalChargedToDate")] Contract contract)
        {
            if (ModelState.IsValid)
            {
                _context.Add(contract);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Customer, "CustomerId", "CustomerId", contract.CustomerId);
            return View(contract);
        }

        // GET: HKContract/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contract = await _context.Contract.FindAsync(id);
            if (contract == null)
            {
                return NotFound();
            }
            ViewData["CustomerId"] = new SelectList(_context.Customer, "CustomerId", "CustomerId", contract.CustomerId);
            return View(contract);
        }

        // POST: HKContract/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ContractId,CustomerId,Name,StartDate,DaysDuration,QuotedPrice,Closed,TotalChargedToDate")] Contract contract)
        {
            if (id != contract.ContractId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contract);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContractExists(contract.ContractId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Customer, "CustomerId", "CustomerId", contract.CustomerId);
            return View(contract);
        }

        // GET: HKContract/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contract = await _context.Contract
                .Include(c => c.Customer)
                .FirstOrDefaultAsync(m => m.ContractId == id);
            if (contract == null)
            {
                return NotFound();
            }

            return View(contract);
        }

        // POST: HKContract/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contract = await _context.Contract.FindAsync(id);
            _context.Contract.Remove(contract);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContractExists(int id)
        {
            return _context.Contract.Any(e => e.ContractId == id);
        }
    }
}

Consulting/Controllers/HKWorkSessionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using Consulting.Models;

namespace Consulting.Controllers
{
    public class HKWorkSessionsController : Controller
    {
        private readonly ConsultingContext _context;

        public HKWorkSessionsController(ConsultingContext context)
        {
            _context = context;
        }

        // GET: HKWorkSessions
        public async Task<IActionResult> Index(int? id)
        {
            if(id != null)
            {
                HttpContext.Session.SetInt32("ContractID", (int)id);
            }
            else
            {
                if(HttpContext.Session.GetInt32("ContractID") == null)
                {
                    TempData["Message"] = "No record to show";
                    return RedirectToAction("Index", "HKContract");
                }
                else
                {
                    id = HttpContext.Session.GetInt32("ContractID");
                }
            }

            if (!_context.WorkSession.Where(a => a.ContractId == id).Any())
            {
                //var contracName = _context.Contract.Where(a => a.ContractId == id).Select(a => a.Name).FirstOrDefaultAsync();
                var contractName = _context.Contract.Where(a => a.ContractId == id).FirstOrDefault().Name;
                TempData["Message"] = $"no work session exist for contract {contractName}";

                return View();
            }

            //var consultingContext = _context.WorkSession
            //                            .Include(w => w.Consultant)
            //                            .Include(w => w.Contract)
            //                            .Where(w => w.ContractId == id);
            var consultingContext =  _context.WorkSession
                                        .Include(w => w.Consultant)
                                        .Include(w => w.Contract)
                                        .Where(w => w.ContractId == id);


            double totalHour = 0.0, totalCost = 0.0, provincialTax = 0.0;

            var customerID = _context.Contract.Where(a => a.ContractId == id).FirstOrDefault().CustomerId;
            var customerProvince = _context.Customer.Where(a => a.CustomerId == customerID).FirstOrDefault().ProvinceCode;
            provincialTax = Convert.ToDouble(_context.Province.Where(a => a.ProvinceCode ==  customerProvince).FirstOrDefault().ProvincialTax);

            foreach (var item in consultingContext)
            {
                totalHour += (double)item.HoursWorked;
                totalCost += (double)item.HourlyRate;
            }

            totalCost = totalHour * totalCost * (1.0+provincialTax);
            TempData["Message"] = $"Total hours {totalHour} and total cost {string.Format("{0:c2}",totalCost)}";
            ViewBag.provincialTax = provincialTax;
            return View(await consultingContext.ToListAsync());
        }

        // GET: HKWorkSessions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workSession = await _context.WorkSession
                .Include(w => w.Consultant)
                .Include(w => w.Contract)
                .FirstOrDefaultAsync(m => m.WorkSessionId == id);
            if (workSession == null)
            {
                return NotFound();
            }

            return View(workSession);
        }

        // GET: HKWorkSessions/Create
        public IActionResult Create()
        {
            int contractID = (int)HttpContext.Session.GetInt32("ContractID");

            if(_context.Contract.Where(w => w.ContractId == contractID && w.Closed).Any())
            {
                TempData["Message"] = "Work session cannot be created because contract was closed";
                //return RedirectToAction("Index", "HKWorkSesstion");
                return RedirectToAction(nameof(Index));
            }
            //ViewData["ConsultantId"] = new SelectList(_context.Consultant, "ConsultantId", "FirstName");
            //ViewData["ContractId"] = new SelectList(_context.Contract, "ContractId", "Name");

            WorkSession ws = new WorkSession();
            ws.ContractId = contractID;
            ws.HourlyRate = 0;
            ws.ProvincialTax = 0;
            ws.TotalChargeBeforeTax = 0;

            return View(ws);
        }

        // POST: HKWorkSessions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("WorkSessionId,ContractId,DateWorked,ConsultantId,HoursWorked,WorkDescription,HourlyRate,ProvincialTax,TotalChargeBeforeTax")] WorkSession workSession)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(workSession);
                    await _context.SaveChangesAsync();
                    TempData["Message"] = "added";
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {
                TempData["Message"] = "Create exception: " + ex.GetBaseException().Message;
            }
            //ViewData["ConsultantId"] = new SelectList(_context.Consultant, "ConsultantId", "FirstName", workSession.ConsultantId);
            //ViewData["ContractId"] = new SelectList(_context.Contract, "ContractId", "Name", workSession.ContractId);
            return View(workSession);
        }

        // GET: HKWorkSessions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            int contractID = (int)HttpContext.Session.GetInt32("ContractID");

            if (_context.Contract.Where(a=>a.ContractId == contractID && a.Closed).Any())
            {
                TempData["Message"] = "No work session exist because contract is closed";
                return RedirectToAction(nameof(Index));
            }

            var workSession = await _context.WorkSession.FindAsync(id);
            if (workSession == null)
            {
                return NotFound();
            }
            ViewData["ConsultantId"] = new SelectList(_context.Consultant, "ConsultantId", "FirstName", workSession.ConsultantId);
            ViewData["ContractId"] = new SelectList(_context.Contract, "ContractId", "Name", workSession.ContractId);
            return View(workSession);
        }

        // POST: HKWorkSessions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("WorkSessionId,ContractId,DateWorked,ConsultantId,HoursWorked,WorkDescription,HourlyRate,ProvincialTax,TotalChargeBeforeTax")] WorkSession workSession)
        {
            if (id != workSession.WorkSessionId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    try
                    {
                        _context.Update(workSession);
                        await _context.SaveChangesAsync();
                        TempData["Message"] = "Updated";
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!WorkSessionExists(workSession.WorkSessionId))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    TempData["Message"] = ex.GetBaseException().Message;
                }
            }
            //ViewData["ConsultantId"] = new SelectList(_context.Consultant, "ConsultantId", "FirstName", workSession.ConsultantId);
            //ViewData["ContractId"] = new SelectList(_context.Contract, "ContractId", "Name", workSession.ContractId);
            return View(workSession);
        }

        // GET: HKWorkSessions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workSession = await _context.WorkSession
                .Include(w => w.Consultant)
                .Include(w => w.Contract)
                .FirstOrDefaultAsync(m => m.WorkSessionId == id);
            if (workSession == null)
            {
                return NotFound();
            }

            return View(workSession);
        }

        // POST: HKWorkSessions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var workSession = await _context.WorkSession.FindAsync(id);
            _context.WorkSession.Remove(workSession);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WorkSessionExists(int id)
        {
            return _context.WorkSession.Any(e => e.WorkSessionId == id);
        }
    }
}

Consulting/Views/HKContract/Create.cshtml
@model Consulting.Models.Contract

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Contract</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <select asp-for="CustomerId" class ="form-control" asp-items="ViewBag.CustomerId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DaysDuration" class="control-label"></label>
                <input asp-for="DaysDuration" class="form-control" />
                <span asp-validation-for="DaysDuration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="QuotedPrice" class="control-label"></label>
                <input asp-for="QuotedPrice" class="form-control" />
                <span asp-validation-for="QuotedPrice" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Closed" /> @Html.DisplayNameFor(model => model.Closed)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="TotalChargedToDate" class="control-label"></label>
                <input asp-for="TotalChargedToDate" class="form-control" />
                <span asp-validation-for="TotalChargedToDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Consulting/Views/HKContract/Delete.cshtml
@model Consulting.Models.Contract

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Contract</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DaysDuration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DaysDuration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QuotedPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QuotedPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Closed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Closed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalChargedToDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalChargedToDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer.CustomerId)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ContractId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Consulting/Views/HKContract/Details.cshtml
@model Consulting.Models.Contract

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Contract</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DaysDuration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DaysDuration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.QuotedPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.QuotedPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Closed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Closed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalChargedToDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalChargedToDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer.CustomerId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ContractId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Consulting/Views/HKContract/Edit.cshtml
@model Consulting.Models.Contract

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Contract</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ContractId" />
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <select asp-for="CustomerId" class="form-control" asp-items="ViewBag.CustomerId"></select>
                <span asp-validation-for="CustomerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DaysDuration" class="control-label"></label>
                <input asp-for="DaysDuration" class="form-control" />
                <span asp-validation-for="DaysDuration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="QuotedPrice" class="control-label"></label>
                <input asp-for="QuotedPrice" class="form-control" />
                <span asp-validation-for="QuotedPrice" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Closed" /> @Html.DisplayNameFor(model => model.Closed)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="TotalChargedToDate" class="control-label"></label>
                <input asp-for="TotalChargedToDate" class="form-control" />
                <span asp-validation-for="TotalChargedToDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Consulting/Views/HKContract/Index.cshtml
@model IEnumerable<Consulting.Models.Contract>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DaysDuration)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.QuotedPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Closed)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalChargedToDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Customer)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a asp-controller="HKWorkSessions" asp-action="Index" asp-route-id="@item.ContractId"> @Html.DisplayFor(modelItem => item.Name)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DaysDuration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QuotedPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Closed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalChargedToDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer.CustomerId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ContractId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ContractId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ContractId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>